from portfolio_client import PortfolioClient
import os
import json
import mimetypes

client = PortfolioClient()

# ---------- LOGIN ----------
ok, _ = client.login(
    email="kavidudharmasiri90@gmail.com",
    password="WinstonK123"
)
if not ok:
    print("❌ Admin login failed")
    print(_)
    exit()

certificates = [
    {
        "name": "Decoding DevOps – From Basics to Advanced Projects with AI ",
        "issuer": "Udemy",
        "issueDate": "2025-10-22",
        "credentialsId": "UC-73e0ea6a-97d7-4c82-aa4f-f76e49b61444",
        "certificateLink": "https://www.udemy.com/certificate/UC-73e0ea6a-97d7-4c82-aa4f-f76e49b61444/",
        "tags": ["Devops", "Linux", "Git", "Docker", "Kubernetes", "CI/CD", "Cloud", "AI", "Vegrant", "Scripting", "AWS", "Jenkins", "Nexus", "SonarQube", "Ansible", "Terraform", "Python Automation", "GitHub Actions", "Gitops"],
        "score": 99,
        "image": "../assets/certImages/Decoding-DevOps---From-Basics-to-Advanced-Projects-with-AI.jpg",
    },
    {
        "name": "Docker and Kubernetes: The Complete Course from Zero to Hero",
        "issuer": "Udemy",
        "issueDate": "2025-11-23",
        "credentialsId": "UC-675c4847-aead-4075-b57c-97c9e6a46cbb",
        "certificateLink": "https://www.udemy.com/certificate/UC-675c4847-aead-4075-b57c-97c9e6a4bcbb/",
        "tags": ["Docker", "Kubernetes", "Docker Compose", "Kustomize", "Containerization", "Orchestration", "Microservices", "Cloud Native", "DevOps", "CI/CD", "GCP"],
        "score": 98,
        "image": "../assets/certImages/Docker-and-Kubernetes-The-Complete-Course-from-Zero-to-Hero.jpg",
    },
    {
        "name": "AWS Cloud Technical Essentials",
        "issuer": "Coursera - AWS",
        "issueDate": "2024-06-20",
        "credentialsId": "MUH4C7ENAGAU",
        "certificateLink": "https://www.coursera.org/account/accomplishments/records/MUH4C7ENAGAU",
        "tags": ["AWS", "Cloud Computing", "Cloud Architecture", "AWS Services", "Cloud Security", "Cloud Migration", "AWS Management Tools", "AWS Pricing and Support", "EC2", "S3", "RDS", "Lambda", "VPC", "IAM", "CloudWatch", "DynamoDB"],
        "score": 97,
        "image": "../assets/certImages/AWS-Cloud-Technical-Essentials.jpg",
    },
    {
        "name": "Mastering TypeScript – 2026 Edition",
        "issuer": "Udemy",
        "issueDate": "2026-01-09",
        "credentialsId": "UC-532afb6a-0859-42d2-a820-495b1c48c5f7",
        "certificateLink": "https://www.udemy.com/certificate/UC-532afb6a-0859-42d2-a820-495b1c48c5f7/",
        "tags": ["typescript", "typescript advanced", "typescript compiler", "typescript dom", "typescript classes", "typescript generics", "webpack typescript", "react typescript"],
        "score": 90,
        "image": "../assets/certImages/Mastering-TypeScript-–-2026-Edition.jpg",
    },
    {
        "name": "Programming for Everybody (Getting Started with Python)",
        "issuer": "Coursera-University of Michigan",
        "issueDate": "2024-07-24",
        "credentialsId": "D4A52A8GSVRD",
        "certificateLink": "https://www.coursera.org/account/accomplishments/records/D4A52A8GSVRD",
        "tags": ["python", "programming", "beginner", "coursera", "university of michigan"],
        "score": 85,
        "image": "../assets/certImages/Programming-for-Everybody-Getting-Started-with-Python.png",
    },
    {
        "name": "Developing AI Applications with Python and Flask",
        "issuer": "Coursera - IBM",
        "issueDate": "2024-07-24",
        "credentialsId": "ZLZ9F3H9PL86",
        "certificateLink": "https://www.coursera.org/account/accomplishments/records/ZLZ9F3H9PL86",
        "tags": ["python", "flask", "ai applications", "coursera", "ibm", "web development"],
        "score": 85,
        "image": "../assets/certImages/Developing-AI-Applications-with-Python-and-Flask.png",
    },
    {
        "name": "Implement GitOps principles (pull based) with Azure Cloud (AKS), AWS and create project infrastructure using Terraform",
        "issuer": "Udemy",
        "issueDate": "2025-10-24",
        "credentialsId": "UC-de40f18d-9e8b-4e25-8cac-98404d675c55",
        "certificateLink": "https://www.udemy.com/certificate/UC-de401f8d-9e8b-4e25-8cac-98404d675c55/",
        "tags": ["GitOps", "Azure Cloud", "AKS", "AWS", "Terraform", "Infrastructure as Code", "Cloud Native", "DevOps", "CI/CD", "Kubernetes"],
        "score": 90,
        "image": "../assets/certImages/Implement-GitOps-principles-pull-based-with-Azure-Cloud-AKS-AWS-and-create-project-infrastructure-using-Terraform.jpg",
    },
    {
        "name": "A complete guide to configuration management and orchestration with Ansible",
        "issuer": "Udemy",
        "issueDate": "2025-10-13",
        "credentialsId": "UC-8cf4c478-3e10-40b0-aa0d-bc063c9f6ded",
        "certificateLink": "https://www.udemy.com/certificate/UC-8cfe4c78-3e10-40b0-aa0d-bc063c9f6ded/",
        "tags": ["Ansible", "Configuration Management", "DevOps", "Infrastructure as Code", "Automation", "Ansible Playbooks", "Ansible Roles"],
        "score": 90,
        "image": "../assets/certImages/A-complete-guide-to-configuration-management-and-orchestration-with-Ansible.jpg",
    },
    {
        "name": "KodeKloud Engineer - Git (Level 1)",
        "issuer": "KodeKloud",
        "issueDate": "2025-10-04",
        "credentialsId": "46c21758-d09a-42b8-bbf9-8a0ba47a3b4a",
        "certificateLink": "https://engineer.kodekloud.com/certificate-verification/46c21758-d09a-42b8-bbf9-8a0ba47a3b4a",
        "tags": ["Git", "Version Control", "KodeKloud"],
        "score": 70,
        "image": "../assets/certImages/KodeKloud-Engineer-Git-Level-1.png",
    },
    {
        "name": "KodeKloud Engineer - Docker (Level 1)",
        "issuer": "KodeKloud",
        "issueDate": "2025-09-28",
        "credentialsId": "6397b91e-e8bb-47ec-8a41-15afe087cc08",
        "certificateLink": "https://engineer.kodekloud.com/certificate-verification/6397b91e-e8bb-47ec-8a41-15afe087cc08",
        "tags": ["Docker", "Containerization", "KodeKloud"],
        "score": 75,
        "image": "../assets/certImages/KodeKloud-Engineer-Docker-Level-1.png",
    },
    {
        "name": "Labs : Ansible for the Absolute Beginners",
        "issuer": "KodeKloud",
        "issueDate": "2025-09-26",
        "credentialsId": "ea7d71b9-821b-4a57-9778-099074db8bc8",
        "certificateLink": "https://learn.kodekloud.com/certificate/ea7d71b9-821b-4a57-9778-099074db8bc8",
        "tags": ["Ansible", "Configuration Management", "KodeKloud"],
        "score": 70,
        "image": "../assets/certImages/Labs-Ansible-for-the-Absolute-Beginners.png",
    },
    {
        "name": "Ansible for the Absolute Beginner - Hands-On - DevOps",
        "issuer": "Udemy",
        "issueDate": "2025-09-26",
        "credentialsId": "UC-627ceaad-4794-46b7-afd1-3cef450daaef",
        "certificateLink": "https://www.udemy.com/certificate/UC-627ceaad-4794-46b7-a1d1-3cef450daaef/",
        "tags": ["Ansible", "Configuration Management", "DevOps", "Automation", "Ansible Playbooks", "Ansible Roles"],
        "score": 85,
        "image": "../assets/certImages/Ansible-for-the-Absolute-Beginner-Hands-On-DevOps.jpg",
    },
    {
        "name": "DevOps Project 1 - CI/CD with Git Jenkins Ansible Kubernetes",
        "issuer": "Udemy",
        "issueDate": "2025-09-24",
        "credentialsId": "UC-f5043c88-79b3-4a06-a5cf-497a5b1fcca7",
        "certificateLink": "https://www.udemy.com/certificate/UC-f5043c88-79b3-4a06-a5cf-497a5b1fcca7/",
        "tags": ["DEvOps", "CI/CD", "Git", "Jenkins", "Ansible", "Kubernetes", "CI/CD Pipeline", "Automation", "Cloud Native", "AWS"],
        "score": 90,
        "image": "../assets/certImages/DevOps-Project-1-CI-CD-with-Git-Jenkins-Ansible-Kubernetes.jpg",
    },
    {
        "name": "SonarQube for Continuous Inspection and Code Review",
        "issuer": "Edureka",
        "issueDate": "2025-09-07",
        "credentialsId": "3X1XRQAMMC1Z",
        "certificateLink": "https://www.coursera.org/account/accomplishments/records/3X1XRQAMMC1Z",
        "tags": ["SonarQube", "Continuous Inspection", "Code Review", "Edureka"],
        "score": 65,
        "image": "../assets/certImages/SonarQube-for-Continuous-Inspection-and-Code-Review.png",
    },
    {
        "name": "Continuous Integration & Continuous Deployment with Jenkins",
        "issuer": "LearnKartS - Customized eLearning Content Provider",
        "issueDate": "2025-10-13",
        "credentialsId": "WRVDY2TLUUKT",
        "certificateLink": "https://www.coursera.org/account/accomplishments/records/WRVDY2TLUUKT",
        "tags": ["CI/CD", "Jenkins", "LearnKartS"],
        "score": 70,
        "image": "../assets/certImages/Continuous-Integration-and-Continuous-Deployment-with-Jenkins.png",
    },
    {
        "name": "Fundamentals of Ansible",
        "issuer": "Coursera-Red Hat",
        "issueDate": "2025-09-06",
        "credentialsId": "M24FVVGJQTYV",
        "certificateLink": "https://www.coursera.org/account/accomplishments/records/M24FVVGJQTYV",
        "tags": ["Ansible", "Configuration Management", "Coursera", "Red Hat"],
        "score": 85,
        "image": "../assets/certImages/Fundamentals-of-Ansible.png",
    },
    {
        "name": "Getting Started with Google Kubernetes Engine",
        "issuer": "Coursera - Google Cloud",
        "issueDate": "2025-09-05",
        "credentialsId": "TAOL3IJCXTTL",
        "certificateLink": "https://www.coursera.org/account/accomplishments/records/TAOL3IJCXTTL",
        "tags": ["Google Kubernetes Engine", "Kubernetes", "Google Cloud", "Coursera"],
        "score": 75,
        "image": "../assets/certImages/Getting-Started-with-Google-Kubernetes-Engine.png",
    },
    {
        "name": "Jenkins : Automating your delivery pipeline",
        "issuer": "Coursera Project Network",
        "issueDate": "2025-09-02",
        "credentialsId": "L2OA9V62UDDJ",
        "certificateLink": "https://www.coursera.org/account/accomplishments/verify/L2OA9V62UDDJ",
        "tags": ["Jenkins", "CI/CD", "DevOps"],
        "score": 70,
        "image": "../assets/certImages/Jenkins-Automating-your-delivery-pipeline.png",
    },
    {
        "name": "Introduction to Containers w/ Docker, Kubernetes & OpenShift",
        "issuer": "Coursera - IBM",
        "issueDate": "2024-07-20",
        "credentialsId": "YBPKCGNRRRGT",
        "certificateLink": "https://www.coursera.org/account/accomplishments/records/YBPKCGNRRRGT",
        "tags": ["Containers", "Docker", "Kubernetes", "OpenShift", "Coursera", "IBM"],
        "score": 85,
        "image": "../assets/certImages/Introduction-to-Containers-w-Docker-Kubernetes-OpenShift.png",
    },
    {
        "name": "Getting Started with Git and GitHub",
        "issuer": "Coursera - IBM",
        "issueDate": "2024-07-07",
        "credentialsId": "JYN8NRH4YVU5",
        "certificateLink": "https://www.coursera.org/account/accomplishments/records/JYN8NRH4YVU5",
        "tags": ["Git", "GitHub", "Version Control", "Coursera", "IBM"],
        "score": 80,
        "image": "../assets/certImages/Getting-Started-with-Git-and-GitHub.png",
    },
    {
        "name": "Become an Azure Expert! Learn to design and build modern cloud apps from a certified Azure Architect",
        "issuer": "Udemy",
        "issueDate": "2025-04-05",
        "credentialsId": "UC-2bcb27e3-86bd-4737-990c-218946109434",
        "certificateLink": "https://udemy-certificate.s3.amazonaws.com/image/UC-2bcb27e3-86bd-4737-990c-218946109434.jpg",
        "tags": ["Azure", "Azure Computing", "Cloud Architecture", "Azure Virtual Machines", "Azure Storage", "Azure SQL Database", "Azure Functions", "Azure Virtual Network", ],
        "score": 90,
        "image": "../assets/certImages/Become-an-Azure-Expert-Learn-to-design-and-build-modern-cloud-apps-from-a-certified-Azure-Architect.jpg",
    },
    {
        "name": "Python for Serverless Applications and Automation on AWS",
        "issuer": "Coursera - AWS",
        "issueDate": "2025-03-21",
        "credentialsId": "4EJXRI9WPWXD",
        "certificateLink": "https://www.coursera.org/account/accomplishments/records/4EJXRI9WPWXD",
        "tags": ["Python", "Serverless", "AWS", "Automation", "Coursera", "RDS", "Lambda"],
        "score": 85,
        "image": "../assets/certImages/Python-for-Serverless-Applications-and-Automation-on-AWS.png",
    },
    {
        "name": "Introduction to Microsoft Azure Cloud Services",
        "issuer": "Coursera - Microsoft",
        "issueDate": "2025-03-14",
        "credentialsId": "SFGBRZ4P48TS  ",
        "certificateLink": "https://www.coursera.org/account/accomplishments/records/SFGBRZ4P48TS",
        "tags": ["Microsoft Azure", "Azure Cloud Services", "Cloud Computing", "Coursera", "Microsoft"],
        "score": 75,
        "image": "../assets/certImages/Introduction-to-Microsoft-Azure-Cloud-Services.png",
    },
    {
        "name": "Skills and Best Practices for Cloud Support Associates",
        "issuer": "Coursera - AWS",
        "issueDate": "2024-12-22",
        "credentialsId": "RXTTUC0EGIX8",
        "certificateLink": "https://www.coursera.org/account/accomplishments/verify/RXTTUC0EGIX8",
        "tags": ["Cloud Support", "AWS", "Coursera", "Generative AI", "Cloud Computing"],
        "score": 70,
        "image": "../assets/certImages/Skills-and-Best-Practices-for-Cloud-Support-Associates.png",
    },
    {
        "name": "Introduction to Information Technology and AWS Cloud",
        "issuer": "Coursera - AWS",
        "issueDate": "2024-12-07",
        "credentialsId": "YC94TNGV83K3",
        "certificateLink": "https://www.coursera.org/account/accomplishments/records/YC94TNGV83K3",
        "tags": ["Information Technology", "AWS Cloud", "Cloud Computing", "Coursera", "AWS"],
        "score": 70,
        "image": "../assets/certImages/Introduction-to-Information-Technology-and-AWS-Cloud.png",
    },
    {
        "name": "Developing Applications on AWS Specialization",
        "issuer": "Coursera - AWS",
        "issueDate": "2024-06-19",
        "credentialsId": "NAYM2G3P14AF",
        "certificateLink": "https://s3.amazonaws.com/coursera_assets/meta_images/generated/CERTIFICATE_LANDING_PAGE/CERTIFICATE_LANDING_PAGE~NAYM2G3P14AF/CERTIFICATE_LANDING_PAGE~NAYM2G3P14AF.jpeg",
        "tags": ["DevOps", "Serverless Computing", "Cloud API", "IAM", "Continuous Delivery", "Application Deployment", "API Gateway", "Version Control", "Amazon DynamoDB", "Git ", "CI/CD"],
        "score": 85,
        "image": "../assets/certImages/Developing-Applications-on-AWS-Specialization.png",
    },
    {
        "name": "Hands-on with AWS: Software Development Practices",
        "issuer": "Coursera - AWS",
        "issueDate": "2024-08-04",
        "credentialsId": "OPF7J50CRZSB",
        "certificateLink": "https://www.coursera.org/account/accomplishments/records/OPF7J50CRZSB",
        "tags": ["Git", "Software Testing", "Continuous Delivery", "Continuous Integration", "CI/CD", "Software Development", "Application Deployment", "Unit Testing", "Test Automation", "Version Control"],
        "score": 75,
        "image": "../assets/certImages/Hands-on-with-AWS-Software-Development-Practices.png",
    },
    {
        "name": "Integrating AWS with the SDK",
        "issuer": "Coursera - AWS",
        "issueDate": "2024-07-06",
        "credentialsId": "WCDZZG3VNW7D",
        "certificateLink": "https://www.coursera.org/account/accomplishments/records/WCDZZG3VNW7D",
        "tags": ["AWS SDK", "AWS", "Cloud API", "Serverless Computing", "Amazon DynamoDB", "API Gateway", "Amazon S3", "AWS Identity and Access Management (IAM)", "NoSQL"],
        "score": 75,
        "image": "../assets/certImages/Integrating-AWS-with-the-SDK.png",
    },
    {
        "name": "Serverless Architectures on AWS",
        "issuer": "Coursera - AWS",
        "issueDate": "2024-07-25",
        "credentialsId": "DZDWED2UUHGJ",
        "certificateLink": "https://www.coursera.org/account/accomplishments/records/DZDWED2UUHGJ",
        "tags": ["Event-Driven", "Authentications", "Automation", "Amazon DynamoDB", "AWS CloudFormation", "Serverless Computing", "Amazon S3", "API Gateway", "Cloud Infrastructure",],
        "score": 80,
        "image": "../assets/certImages/Serverless-Architectures-on-AWS.png",
    },
    {
        "name": "Learn Elementor – Elementor for WordPress",
        "issuer": "Udemy",
        "issueDate": "2025-06-24",
        "credentialsId": "UC-cd12b14a-4653-4a74-b0fc-d397a4ba105f",
        "certificateLink": "https://www.udemy.com/certificate/UC-cd12b14a-4653-4a74-b0fc-d397a4ba105f/",
        "tags": ["Elementor", "WordPress", "Web Design", "Web Development"],
        "score": 90,
        "image": "../assets/certImages/Learn-Elementor-Elementor-for-WordPress.jpg",
    },
    {
        "name": "OpenAPI Specification & Swagger Tools – Zero To Master",
        "issuer": "Udemy",
        "issueDate": "2025-12-25",
        "credentialsId": "UC-50938c73-637a-4c54-847f-ab22b6d8b3b4",
        "certificateLink": "https://www.udemy.com/certificate/UC-50938c73-637a-4c54-847f-ab22b6d8b3b4/",
        "tags": ["OpenAPI", "Swagger", "API Documentation", "API Design", "API Development", "API Testing"],
        "score": 90,
        "image": "../assets/certImages/OpenAPI-Specification-Swagger-Tools-Zero-To-Master.jpg",
    },
    {
        "name": "Python for Machine Learning & Data Science Masterclass",
        "issuer": "Udemy",
        "issueDate": "2024-06-15",
        "credentialsId": "UC-2a76c813-9235-468f-81c8-f26827c3c9f8",
        "certificateLink": "https://udemy-certificate.s3.amazonaws.com/image/UC-2a76c813-9235-468f-81c8-f26827c3c9f8.jpg?v=1718427208000",
        "tags": ["Python", "Machine Learning", "Data Science", "Regression", "Classification", "Clustering", "Deep Learning", "Data Visualization"],
        "score": 90,
        "image": "../assets/certImages/Python-for-Machine-Learning-Data-Science-Masterclass.jpg",
    },
    {
        "name": "Deploy a Production Machine Learning model with AWS & React",
        "issuer": "Udemy",
        "issueDate": "2024-07-23",
        "credentialsId": "UC-2fa73bbf-ff4a-4928-87e8-bf9010c091fd",
        "certificateLink": "https://udemy-certificate.s3.amazonaws.com/image/UC-2fa73bbf-f1fa-4928-87e8-bf9010c09f1d.jpg?v=1721752591000",
        "tags": ["AWS", "React", "Machine Learning", "Production Deployment", "Cloud Computing"],
        "score": 85,
        "image": "../assets/certImages/Deploy-a-Production-Machine-Learning-model-with-AWS-React.jpg",
    },
    {
        "name": "Build an AWS Machine Learning Pipeline for Object Detection",
        "issuer": "Udemy",
        "issueDate": "2024-07-05",
        "credentialsId": "UC-4f1e54a5-4dd0-4102-ac7a-733f5541ead6",
        "certificateLink": "https://udemy-certificate.s3.amazonaws.com/image/UC-4f1e54a5-4dd0-4102-ac7a-733f5541ead6.jpg?v=1720179984000",
        "tags": ["AWS", "Machine Learning", "Object Detection", "Pipeline", "Cloud Computing"],
        "score": 85,
        "image": "../assets/certImages/Build-an-AWS-Machine-Learning-Pipeline-for-Object-Detection.jpg",
    },
    {
        "name": "Supervised Machine Learning: Regression and Classification ",
        "issuer": "Coursera - Deeplearning.ai",
        "issueDate": "2024-07-22",
        "credentialsId": "562CJ46SZ2YR",
        "certificateLink": "https://www.coursera.org/account/accomplishments/records/562CJ46SZ2YR",
        "tags": ["Supervised Learning", "Machine Learning", "Regression", "Classification", "Coursera", "Deeplearning.ai"],
        "score": 90,
        "image": "../assets/certImages/Supervised-Machine-Learning-Regression-and-Classification.png",
    },
    {
        "name": "Microsoft Azure Machine Learning for Data Scientists",
        "issuer": "Coursera - Microsoft",
        "issueDate": "2024-07-15",
        "credentialsId": "CPYAMFTLT4MK",
        "certificateLink": "https://www.coursera.org/account/accomplishments/records/CPYAMFTLT4MK",
        "tags": ["Azure", "Machine Learning", "Data Science", "Coursera", "Microsoft"],
        "score": 80,
        "image": "../assets/certImages/Microsoft-Azure-Machine-Learning-for-Data-Scientists.png",
    },
    {
        "name": "Neural Networks and Deep Learning",
        "issuer": "Coursera - Deeplearning.ai",
        "issueDate": "2024-08-19",
        "credentialsId": "NETCB2ITOHMM",
        "certificateLink": "https://www.coursera.org/account/accomplishments/records/NETCB2ITOHMM",
        "tags": ["Neural Networks", "Deep Learning", "Coursera", "Deeplearning.ai"],
        "score": 90,
        "image": "../assets/certImages/Neural-Networks-and-Deep-Learning.png",
    },
    {
        "name": "Create Machine Learning Models in Microsoft Azure",
        "issuer": "Coursera - Microsoft",
        "issueDate": "2024-07-03",
        "credentialsId": "3EV7W6PFAYQ6",
        "certificateLink": "https://www.coursera.org/account/accomplishments/records/3EV7W6PFAYQ6",
        "tags": ["Azure", "Machine Learning", "Data Science", "Coursera", "Microsoft"],
        "score": 80,
        "image": "../assets/certImages/Create-Machine-Learning-Models-in-Microsoft-Azure.png",
    },
    {
        "name": "Figma UI UX Design Essentials",
        "issuer": "Udemy",
        "issueDate": "2024-01-27",
        "credentialsId": "UC-562a8bad-65dc-43bf-ac81-ae084b0ae808",
        "certificateLink": "https://udemy-certificate.s3.amazonaws.com/image/UC-562a8bad-65dc-43bf-ac81-ae084b0ae808.jpg?v=1732651933000",
        "tags": ["UI", "UX", "Design", "Figma", "Udemy"],
        "score": 90,
        "image": "../assets/certImages/Figma-UI-UX-Design-Essentials.png",
    },
    {
        "name": "Hands-on Introduction to Linux Commands and Shell Scripting",
        "issuer": "Coursera - IBM",
        "issueDate": "2024-07-27",
        "credentialsId": "L5V84AQ8CE7Z",
        "certificateLink": "https://www.coursera.org/account/accomplishments/records/L5V84AQ8CE7Z",
        "tags": ["Linux", "Commands", "Shell Scripting", "Coursera", "IBM"],
        "score": 85,
        "image": "../assets/certImages/Hands-on-Introduction-to-Linux-Commands-and-Shell-Scripting.png",
    },


]

url = f"{client.base_url}/certificate"

for cert in certificates:
    if not os.path.exists(cert["image"]):
        print(f"❌ Image not found: {cert['name']}")
        continue

    data = {
        "name": cert["name"],
        "issuer": cert["issuer"],
        "issueDate": cert["issueDate"],
        "credentialsId": cert["credentialsId"],
        "certificateLink": cert["certificateLink"],
        "tags": json.dumps(cert["tags"]),
        "score": str(cert["score"]),
    }

    mime, _ = mimetypes.guess_type(cert["image"])

    files = {
        "certificate-image": (
            os.path.basename(cert["image"]),
            open(cert["image"], "rb"),
            mime,
        )
    }

    res = client.session.post(url, data=data, files=files)

    if res.status_code == 201:
        print(f"✅ {cert['name']} added")
    else:
        print(f"❌ Failed: {cert['name']}")
        print(res.status_code, res.text)
